from __future__ import annotations
import collections.abc
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import mbe_automation.structure.display
import mbe_automation.calculators.electronic
import mbe_automation.storage.core
import mbe_automation.storage.mbe
from mbe_automation.structure.clusters import UniqueClusters
from mbe_automation.storage.mbe import _MBEMetadata

if TYPE_CHECKING:
    from mbe_automation.storage.core import Structure


@dataclass(kw_only=True)
class MBEMetadata(_MBEMetadata):
    """
    Store metadata and geometric parameters of Many-Body Expansion (MBE) calculations.

    Attributes:
        cluster_types: List of available cluster type identifiers
            (e.g., ["monomers[A]", "dimers[AA]", "dimers[AB]", "trimers[AAA]"]).
        unique_clusters_keys: Mapping of cluster type strings to full dataset keys
            pointing to stored `UniqueClusters` objects in the dataset file.
        crystal_key: Full dataset key for the input crystal structure.
        dataset: Path to the dataset file.
        root_key: Root storage key in the dataset file.
        filter: Filtering configuration used for cluster extraction.
        geometric_parameters: Dictionary mapping cluster type strings (e.g., "monomers[A]",
            "dimers[AA]", "trimers[AAA]") to DataFrames of geometric parameters and symmetry weights
            generated by `UniqueClusters.to_data_frame()`.
    """

    @classmethod
    def read(
        cls,
        dataset: str | Path,
        key: str,
    ) -> MBEMetadata:
        """
        Read MBEMetadata from a dataset file.
        """
        raw = mbe_automation.storage.mbe.read_mbe_metadata(
            dataset=dataset,
            key=key,
        )
        return cls(**vars(raw))

    def read_crystal(self) -> Structure:
        """
        Read input crystal structure from dataset file at crystal_key.
        """
        return mbe_automation.storage.core.read_structure(
            dataset=self.dataset,
            key=self.crystal_key,
        )

    def read_clusters(
        self,
        cluster_type: str | None = None,
    ) -> UniqueClusters | dict[str, UniqueClusters]:
        """
        Read stored symmetry-unique clusters from the dataset file.

        Args:
            cluster_type: Optional cluster type identifier (e.g., "dimers[AA]").
                If None, returns a dictionary containing all cluster types.

        Returns:
            A single `UniqueClusters` object if `cluster_type` is specified,
            or a dictionary mapping cluster types to `UniqueClusters` objects.
        """
        if cluster_type is None:
            return {
                cluster_type: self.read_clusters(
                    cluster_type=cluster_type,
                )
                for cluster_type in self.cluster_types
            }

        assert cluster_type in self.unique_clusters_keys, (
            f"Invalid cluster type: '{cluster_type}'. "
            f"Available cluster types: {self.cluster_types}"
        )

        return mbe_automation.storage.core.read_unique_clusters(
            dataset=self.dataset,
            key=self.unique_clusters_keys[cluster_type],
        )

    def plot(
        self,
        property: str = "cumulative_cluster_count",
        save_path: str | Path | None = None,
    ) -> plt.Figure | None:
        """
        Plot properties of symmetry-unique clusters.

        Args:
            property: Name of the property to plot (default: "cumulative_cluster_count").
            save_path: Optional path where the generated plot will be saved.

        Returns:
            Matplotlib Figure object or None if saved directly.
        """
        if property == "cumulative_cluster_count":
            clusters_dict = self.read_clusters()
            return mbe_automation.structure.display.plot_cumulative_cluster_count(
                unique_clusters=clusters_dict,
                save_path=save_path,
            )
        else:
            raise ValueError(
                f"Invalid plot property: '{property}'. "
                f"Supported properties are: ['cumulative_cluster_count']"
            )

    def to_input_files(
        self,
        dir: str | Path,
        method: mbe_automation.calculators.electronic.Method,
        cluster_types: collections.abc.Sequence[str] | None = None,
    ) -> None:
        """
        Batch generate quantum chemistry input files for clusters.
        """
        selected_types = cluster_types or self.cluster_types
        dir_path = Path(dir)
        for cluster_type in selected_types:
            mbe_automation.calculators.electronic.to_input_files(
                unique_clusters=self.read_clusters(
                    cluster_type=cluster_type,
                ),
                dir=dir_path / cluster_type,
                method=method,
            )

    def to_xyz(
        self,
        dir: str | Path,
        cluster_types: collections.abc.Sequence[str] | None = None,
    ) -> None:
        """
        Batch export .xyz cluster geometries.
        """
        selected_types = cluster_types or self.cluster_types
        dir_path = Path(dir)
        for cluster_type in selected_types:
            self.read_clusters(
                cluster_type=cluster_type,
            ).to_xyz(
                dir=dir_path / cluster_type,
            )

    def to_csv(
        self,
        dir: str | Path,
        cluster_types: collections.abc.Sequence[str] | None = None,
        decimal_digits: int | None = 4,
    ) -> None:
        """
        Batch export .csv metadata files using geometric_parameters.

        Args:
            dir: Destination directory.
            cluster_types: Cluster types to export. If None, exports all cluster types.
            decimal_digits: Number of decimal digits for floating-point formatting.
                If None, full precision is exported.
        """
        selected_types = cluster_types or self.cluster_types
        dir_path = Path(dir)
        dir_path.mkdir(
            parents=True,
            exist_ok=True,
        )
        float_format = (
            f"%.{decimal_digits}f" if decimal_digits is not None else None
        )
        for cluster_type in selected_types:
            if cluster_type in self.geometric_parameters:
                self.geometric_parameters[cluster_type].to_csv(
                    dir_path / f"{cluster_type}.csv",
                    index=False,
                    float_format=float_format,
                )
